name: Halal Insider Trade Scraper (Clean)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  run-scraper:
    name: Run Scraper
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Display Python version (debug)
        run: python --version

      - name: Install dependencies
        run: |
          pip install pandas beautifulsoup4 requests

      - name: Run scraper
        run: python scraper.py

      - name: Commit scraped data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add scraped_trades.csv
          git commit -m "Auto-update scraped_trades.csv" || echo "No changes"
          git push
