name: Daily Insider Trade Scraper

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas beautifulsoup4 requests

      - name: Run scraper
        run: python scraper.py

      - name: Commit scraped data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add scraped_trades.csv
          git commit -m "Auto-update scraped_trades.csv" || echo "No changes"
          git push
